More validation (#30)

diff --git a/snap/hooks/configure b/snap/hooks/configure
--- a/snap/hooks/configure
+++ b/snap/hooks/configure
@@ -8,20 +8,28 @@ layout_list_file="$SNAP/etc/layouts.txt"
 osk_layout_file="$SNAP_DATA/osk-layout.txt"
 osk_gtk_theme_file="$SNAP_DATA/osk-gtk-theme.txt"
 
-osk_layout_option="$(snapctl get layout)"
+osk_layout_option=""
+# Loop through list of layouts ensuring entries are valid and comma separated
+for layout in $(snapctl get layout | sed 's/,/ /g'); do
+  if grep -Fx "$layout" "$layout_list_file" >/dev/null; then
+    if [ -n "${osk_layout_option}" ]; then
+      osk_layout_option="$osk_layout_option,$layout"
+    else
+      osk_layout_option="$layout"
+    fi
+  else
+    echo "Error: $layout is not a valid layout ID." >&2
+    echo "       See $SNAP_NAME.list-layouts for a list of valid layouts." >&2
+    exit 1
+  fi
+done
 if [ -z "${osk_layout_option}" ]; then
   snapctl set "layout=${default_layout_option}"
   osk_layout_option="${default_layout_option}"
+else
+  snapctl set layout="${osk_layout_option}"
 fi
-# Loop through comma-separated list of layouts
-for layout in $(echo "$osk_layout_option" | sed 's/,/ /g'); do
-    # If any layout is not in the layout list, error
-    if ! grep -Fx "$layout" "$layout_list_file" >/dev/null; then
-        echo "Error: $layout is not a valid layout ID." >&2
-        echo "       See $SNAP_NAME.list-layouts for a list of valid layouts." >&2
-        exit 1
-    fi
-done
+
 if [ "$(cat "${osk_layout_file}")" != "${osk_layout_option}" ]; then
   echo "${osk_layout_option}" > "${osk_layout_file}"
   let config_changes+=1
