Validate layout

diff --git a/snap/hooks/configure b/snap/hooks/configure
--- a/snap/hooks/configure
+++ b/snap/hooks/configure
@@ -4,6 +4,7 @@ set -euo pipefail
 config_changes=0
 default_layout_option="us"
 default_theme_option="light"
+layout_list_file="$SNAP/etc/layouts.txt"
 osk_layout_file="$SNAP_DATA/osk-layout.txt"
 osk_gtk_theme_file="$SNAP_DATA/osk-gtk-theme.txt"
 
@@ -11,6 +12,11 @@ osk_layout_option="$(snapctl get layout)"
 if [ -z "${osk_layout_option}" ]; then
   snapctl set "layout=${default_layout_option}"
   osk_layout_option="${default_layout_option}"
+fi
+if ! grep -P '^'"$osk_layout_option"'$' "$layout_list_file" >/dev/null; then
+    echo "Error: ${osk_layout_option} is not a valid layout ID." >&2
+    echo "       See $SNAP_NAME.list-layouts for a list of valid layouts." >&2
+    exit 1
 fi
 if [ "$(cat "${osk_layout_file}")" != "${osk_layout_option}" ]; then
   echo "${osk_layout_option}" > "${osk_layout_file}"
